toolb = nuke.menu('Nodes')
toolb.addCommand('CorderAdd',"nuke.createNode('CorderAdd')")
toolb.addCommand('CorderGamma',"nuke.createNode('CorderGamma')")
toolb.addCommand('CorderContrast',"nuke.createNode('CorderContrast')")
toolb.addCommand('CorderInvert',"nuke.createNode('CorderInvert')")
toolb.addCommand('CorderChannelSwap',"nuke.createNode('CorderChannelSwap')")
toolb.addCommand('CorderOver',"nuke.createNode('CorderOver')")
toolb.addCommand('CorderBlueScreenDifference', "nuke.createNode('CorderBlueScreenDifference')")
toolb.addCommand('CorderSharpen', "nuke.createNode('CorderSharpen')")
toolb.addCommand('CorderMedian', "nuke.createNode('CorderMedian')")
